### ISSUE TITLE
"箱"の実装

### ISSUE THREAD

**Issue by hakusa-aizu** [PandD-Aizu/Minge2023Spring_Team1#25]
"箱"のプログラム仕様

○１マス移動のとき移動先に”箱”が有った場合
    →さらにその一つ先にオブジェクト（ターゲット以外）があったとき、あるいは画面端だったとき
        ”箱”は破壊され,PLは箱のあった場所に移動する
    →さらにその一つ先には何もなかった（移動可能なマスだった）とき
        PLは箱のあった場所に移動し、箱はその一つ先の場所に移動する（要は「押されて動く」）
    →さらにその一つ先にターゲットがあったとき
        PLは箱のあった場所に移動し、箱はそのターゲットがあった場所に移動する
        ターゲットは破壊される

○ダッシュ移動のとき移動先に"箱"があったとき
    →その箱がプレイヤーの1マス隣にあったとき
        PLは通常のダッシュ移動のように端まで移動、箱は破壊される（演出的には箱が端まで移動されたあとで破壊のエフェクトを出す）
    →その箱がプレイヤーの一マス隣ではなかったとき
        箱が柱or壁と同じような容量でPLを止める

画像化したほうがわかりやすいと思うので可能ならやります

**Comment by suzakutakumi** [comment]
プレイヤーの移動方向(ダッシュ時も含む)に箱が2つある場合はその方向に移動できない
ダッシュで箱を押している先に別の箱がある場合、押している箱のみが破壊される
